// Generates the shared canonical face geometry used by every platform.
//
// Two sources, deliberately combined:
//   - canonical_face_model.obj  -> per-vertex UVs (a seamless frontal unwrap)
//   - FACE_LANDMARKS_TESSELATION -> the triangle list
//
// The tessellation is preferred over the OBJ's own 898 faces because it leaves
// the eyes and mouth open, so paint can never land on eyeballs or teeth.
//
// Both clients read the same JSON, which is the point: identical geometry means
// a look painted on one platform lands in the same place on the others.
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, '../..')

// The tessellation is a plain constant in the web client's copy of MediaPipe.
// Pointing at it directly avoids installing a second ~50 MB copy at the root
// just to read one array.
const bundle = join(repoRoot, 'web/node_modules/@mediapipe/tasks-vision/vision_bundle.mjs')
let FaceLandmarker
try {
  ;({ FaceLandmarker } = await import(pathToFileURL(bundle).href))
} catch (error) {
  throw new Error(`Cannot load MediaPipe from ${bundle}. Run \`npm install\` in web/ first.`, {
    cause: error,
  })
}

const VERTEX_COUNT = 468

function parseObj(text) {
  const uvs = []
  // `f` entries reference `vertex/uv`, and the uv list is permuted relative to
  // the vertex list, so the pairing has to be recovered from the faces.
  const uvForVertex = new Array(VERTEX_COUNT).fill(null)

  for (const line of text.split('\n')) {
    if (line.startsWith('vt ')) {
      const [, u, v] = line.split(/\s+/)
      uvs.push([Number(u), Number(v)])
    } else if (line.startsWith('f ')) {
      for (const corner of line.slice(2).trim().split(/\s+/)) {
        const [vertex, uv] = corner.split('/').map((value) => Number(value) - 1)
        if (uvForVertex[vertex] === null) uvForVertex[vertex] = uvs[uv]
      }
    }
  }

  const missing = uvForVertex.findIndex((entry) => entry === null)
  if (missing !== -1) throw new Error(`vertex ${missing} has no UV`)
  return uvForVertex
}

/** Consecutive edge triples close into triangles; verify rather than assume. */
function trianglesFromTessellation(edges) {
  if (edges.length % 3 !== 0) throw new Error(`edge count ${edges.length} is not a multiple of 3`)

  const triangles = []
  for (let i = 0; i < edges.length; i += 3) {
    const [a, b, c] = [edges[i], edges[i + 1], edges[i + 2]]
    const closes = a.end === b.start && b.end === c.start && c.end === a.start
    if (!closes) throw new Error(`edges ${i}..${i + 2} do not form a closed triangle`)
    triangles.push(a.start, b.start, c.start)
  }
  return triangles
}

const obj = await readFile(join(here, 'canonical_face_model.obj'), 'utf8')
const uv = parseObj(obj)
const triangles = trianglesFromTessellation(FaceLandmarker.FACE_LANDMARKS_TESSELATION)

for (const [index, [u, v]] of uv.entries()) {
  if (!(u >= 0 && u <= 1 && v >= 0 && v <= 1)) {
    throw new Error(`vertex ${index} UV out of range: ${u},${v}`)
  }
}
for (const index of triangles) {
  if (index < 0 || index >= VERTEX_COUNT) throw new Error(`triangle index out of range: ${index}`)
}

const payload = {
  $comment:
    'GENERATED by scripts/canonical/generateCanonicalFace.mjs — do not edit. ' +
    'Geometry from MediaPipe canonical_face_model.obj (Apache-2.0); see scripts/canonical/NOTICE.',
  vertexCount: VERTEX_COUNT,
  // Flat [u0, v0, u1, v1, ...] so both clients can upload it straight to a buffer.
  uv: uv.flat().map((value) => Number(value.toFixed(6))),
  triangles,
}

const json = `${JSON.stringify(payload)}\n`
const targets = [
  join(repoRoot, 'web/src/features/render-engine/canonicalFace.json'),
  join(repoRoot, 'apple/Packages/MakeUpCore/Sources/MakeUpCore/Resources/canonicalFace.json'),
]

for (const target of targets) {
  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, json)
}

console.log(`canonical face: ${VERTEX_COUNT} vertices, ${triangles.length / 3} triangles`)
console.log(targets.map((target) => `  -> ${target.replace(`${repoRoot}/`, '')}`).join('\n'))
